 ./gcc-install/bin/gcctiger -c testes/merge.tig &> testes/results/merge.out
 ./gcc-install/bin/gcctiger -c testes/queens.tig &> testes/results/queens.out
 ./gcc-install/bin/gcctiger -c testes/test1.tig &> testes/results/test1.out
 ./gcc-install/bin/gcctiger -c testes/test2.tig &> testes/results/test2.out
 ./gcc-install/bin/gcctiger -c testes/test3.tig &> testes/results/test3.out
 ./gcc-install/bin/gcctiger -c testes/test4.tig &> testes/results/test4.out
 ./gcc-install/bin/gcctiger -c testes/test5.tig &> testes/results/test5.out
 ./gcc-install/bin/gcctiger -c testes/test6.tig &> testes/results/test6.out
 ./gcc-install/bin/gcctiger -c testes/test7.tig &> testes/results/test7.out
 ./gcc-install/bin/gcctiger -c testes/test8.tig &> testes/results/test8.out
 ./gcc-install/bin/gcctiger -c testes/test9.tig &> testes/results/test9.out
 ./gcc-install/bin/gcctiger -c testes/test10.tig &> testes/results/test10.out
 ./gcc-install/bin/gcctiger -c testes/test11.tig &> testes/results/test11.out
 ./gcc-install/bin/gcctiger -c testes/test12.tig &> testes/results/test12.out
 ./gcc-install/bin/gcctiger -c testes/test13.tig &> testes/results/test13.out
 ./gcc-install/bin/gcctiger -c testes/test14.tig &> testes/results/test14.out
 ./gcc-install/bin/gcctiger -c testes/test15.tig &> testes/results/test15.out
 ./gcc-install/bin/gcctiger -c testes/test16.tig &> testes/results/test16.out
 ./gcc-install/bin/gcctiger -c testes/test17.tig &> testes/results/test17.out
 ./gcc-install/bin/gcctiger -c testes/test18.tig &> testes/results/test18.out
 ./gcc-install/bin/gcctiger -c testes/test19.tig &> testes/results/test19.out
 ./gcc-install/bin/gcctiger -c testes/test20.tig &> testes/results/test20.out
 ./gcc-install/bin/gcctiger -c testes/test21.tig &> testes/results/test21.out
 ./gcc-install/bin/gcctiger -c testes/test22.tig &> testes/results/test22.out
 ./gcc-install/bin/gcctiger -c testes/test23.tig &> testes/results/test23.out
 ./gcc-install/bin/gcctiger -c testes/test24.tig &> testes/results/test24.out
 ./gcc-install/bin/gcctiger -c testes/test25.tig &> testes/results/test25.out
 ./gcc-install/bin/gcctiger -c testes/test26.tig &> testes/results/test26.out
 ./gcc-install/bin/gcctiger -c testes/test27.tig &> testes/results/test27.out
 ./gcc-install/bin/gcctiger -c testes/test28.tig &> testes/results/test28.out
 ./gcc-install/bin/gcctiger -c testes/test29.tig &> testes/results/test29.out
 ./gcc-install/bin/gcctiger -c testes/test30.tig &> testes/results/test30.out
 ./gcc-install/bin/gcctiger -c testes/test31.tig &> testes/results/test31.out
 ./gcc-install/bin/gcctiger -c testes/test32.tig &> testes/results/test32.out
 ./gcc-install/bin/gcctiger -c testes/test33.tig &> testes/results/test33.out
 ./gcc-install/bin/gcctiger -c testes/test34.tig &> testes/results/test34.out
 ./gcc-install/bin/gcctiger -c testes/test35.tig &> testes/results/test35.out
 ./gcc-install/bin/gcctiger -c testes/test36.tig &> testes/results/test36.out
 ./gcc-install/bin/gcctiger -c testes/test37.tig &> testes/results/test37.out
 ./gcc-install/bin/gcctiger -c testes/test38.tig &> testes/results/test38.out
 ./gcc-install/bin/gcctiger -c testes/test39.tig &> testes/results/test39.out
 ./gcc-install/bin/gcctiger -c testes/test40.tig &> testes/results/test40.out
 ./gcc-install/bin/gcctiger -c testes/test41.tig &> testes/results/test41.out
 ./gcc-install/bin/gcctiger -c testes/test42.tig &> testes/results/test42.out
 ./gcc-install/bin/gcctiger -c testes/test43.tig &> testes/results/test43.out
 ./gcc-install/bin/gcctiger -c testes/test44.tig &> testes/results/test44.out
 ./gcc-install/bin/gcctiger -c testes/test45.tig &> testes/results/test45.out
 ./gcc-install/bin/gcctiger -c testes/test46.tig &> testes/results/test46.out
 ./gcc-install/bin/gcctiger -c testes/test47.tig &> testes/results/test47.out
 ./gcc-install/bin/gcctiger -c testes/test48.tig &> testes/results/test48.out
 ./gcc-install/bin/gcctiger -c testes/test49.tig &> testes/results/test49.out
rm *.o
